version: '3.8'

services:
  postgres:
    container_name: desafio-pp
    image: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: desafio-pp
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
